### ISSUE TITLE
Aliasing Issues

### ISSUE THREAD

**Issue by kaibuster** [utz82/HoustonTracker2#36]
Howdy, I’m currently running audio out from HT2 on a TI84+ to the audio in on a tracker/sequencer. I’ve been getting some distracting feedback type audio aliasing and wondering if anything can be done to fix this. I can run it through a low pass filter and this fixes the issue but the sound loses a bit of character. Regardless, love the program and hope alls well o7

**Comment by utz82** [comment]
Hi,

Generally I'd recommend to always smoothen out HT2's crude 1-bit sound 
with with a bit of equalization/filtering. That said, I'm not sure if 
the issues you're getting are down to HT2 itself or not. Could you post 
a short sound snippet so I can have a listen?

**Comment by kaibuster** [comment]
/

**Comment by kaibuster** [comment]
Tried uploading the sound clip to GitHub but couldn’t seem to figure that
out. If that file has trouble playing or you need a longer example I can
put something together later tonight after work.

Thanks for always responding so quickly !

**Comment by utz82** [comment]
Yep, that file upload didn't work. Not sure what's going wrong there, 
I've had trouble with Githubs file uploader in the past, too. Perhaps 
zipping the file could work? Or just upload it somewhere else.

**Comment by kaibuster** [comment]
https://soundcloud.com/theserviceclub/ht2-noise

sorry, been a hectic weekend. Uploaded a recording rendered right from the tracker(im using the dirtywave m8). Others have suggested running the HT2 through a low pass filter which does clear the noise but loses some character in the process.

**Comment by utz82** [comment]
Oh, that definitely has more of a whine than it should have. I suspect 
it might be down to a resampling issue. Is it possible to set the m8 to 
a higher sample rate somehow? Failing that, you could try to determine 
the frequency of the whine through spectral analysis and try to put a 
notch there, instead of a low pass.

Other than that, if your batteries are getting a bit low, it's worth 
putting in a fresh set to raise the calc's clock rate. That would 
possibly push the whine to a higher frequency so it's easier to filter out.

**Comment by utz82** [comment]
I'm assuming this is solved, if not feel free to re-open this issue.
